services:
  neo4j:
    image: neo4j:5.20
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc","graph-data-science","bloom"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_server_config_strict__validation_enabled: "false"
      NEO4J_dbms_default__database: shop
    ports: ["7474:7474","7687:7687"]
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import